version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: polin
      MYSQL_ROOT_PASSWORD: polin1111
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/val/lib/redis/data

volumes:
  mysql:
  redis: