spring:
  h2:
    console:
      enabled: true
      path: /h2   # path value is not /h2-console

  datasource:
    include:
      - mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

  redis:
    host: redis
    port: 6379

  message:
    include:
      - message
  email:
    include:
      - email

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

logging:
  level:
    org:
      hibernate: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus






