global:
  scrape_interval: 10s    # 10초마다 Metric을 pulling
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'polin-app'
    metrics_path: '/actuator/prometheus'    # Prometheus endpoint
    static_configs:
      - targets: ['host.docker.internal:8080']    # Application host:post