# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: make application-mysql.yml
      run: |
        cd ./src/main/resources
        touch ./application-mysql.yml
        echo "${{ secrets.DATABASE }}" >> ./application-database.yml
      shell: bash
    
    - name: make application-message.yml
      run: |
          cd ./src/main/resources
          touch ./application-message.yml
          echo "${{ secrets.MESSAGE }}" >> ./application-message.yml
      shell: bash
    
    - name: make application-email.yml
      run: |
        cd ./src/main/resources
        touch ./application-email.yml
        echo "${{ secrets.EMAIL }}" >> ./application-email.yml
      shell: bash
      
    - name: make .env file
      run: |
        touch ./.env
        echo "${{ secrets.ENV }}" >> ./.env
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Test with Gradle
      run: ./gradlew test
      
    - name: docker-compose test
      run: docker-compose up -d --build
  build-docker:
    needs: ci
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
       
      # 하나의 가상 컴퓨터를 구축해주는 소프트웨어
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build with Gradle
        run: ./gradlew clean build
          
      - name: Dockerfile Build
        run: docker build -t polin-backend .
        
      - name: Tag Dockerfile image
        run: docker image tag ${{ secrets.DOCKER_USERNAME }}/hanium-cd

      - name: Dockerfile push to repo
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hanium-cd
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
